language: r
r:
  - 3.4.4

cache: packages
warnings_are_errors: false
r_build_args: --no-build-vignettes --no-manual --no-examples --no-tests
r_check_args: --no-build-vignettes --no-vignettes --no-examples --no-tests
